=== TuTech/DasCMS/System/Resource/DTD/application_v1.dtd
<!ELEMENT bambus (name, description, icon, version, priority, purpose, tabs, application)>
    <!ELEMENT name          (#PCDATA)>
    <!ELEMENT description   (#PCDATA)>
    <!ELEMENT icon          (#PCDATA)>
    <!ELEMENT version       (#PCDATA)>
    <!ELEMENT priority      (#PCDATA)>
    <!ELEMENT purpose       (#PCDATA)>
	<!ELEMENT tabs    		(tab+)>
		<!ELEMENT tab       (#PCDATA)>
		<!ATTLIST tab 
	        icon CDATA #REQUIRED
	     >	
	<!ELEMENT application 	(controller, interface+)>
		<!ELEMENT controller (#PCDATA)>
		<!ELEMENT interface  (task*)>
	    <!ATTLIST interface 
	        name CDATA #REQUIRED
	        src  CDATA #REQUIRED
	     >	
		     <!ELEMENT task EMPTY>
			 <!ATTLIST task 
			    type (button|spacer) #REQUIRED
			    hotkey  CDATA #IMPLIED
			    caption CDATA #IMPLIED
			    icon  	CDATA #IMPLIED
			    action  CDATA #IMPLIED
			    confirm CDATA #IMPLIED
			    name    CDATA #IMPLIED
			    mode    (html|js) #IMPLIED
			 >

=== TuTech/DasCMS/System/Applications/SystemInformation.bap/Application.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bambus SYSTEM "../../Resource/DTD/application_v1.dtd">
<bambus>
	<appController guid="org.bambuscms.applications.systeminformation">ASystemInformation</appController>
	<name>system_information</name>
	<description>view_stats</description>
	<icon>app-system-status</icon>
	<version>0.10.20061011</version>
	<priority>1.9</priority>
	<purpose>system</purpose>
	<tabs>
		<tab icon="action-inform">system_information</tab>
	</tabs>
	<application>
		<controller>controller.php</controller>
		<interface name="system_information" src="info.php">
			<panel name="server_actions">
            	<task type="button" hotkey="R" caption="repair" icon="action-system-repair" action="repair_rights" mode="html" />
            	<task type="button" hotkey="C" caption="clear_cache" icon="action-clean" action="_clear_cache" mode="html" />
            </panel>
		</interface>
	</application>
</bambus>

=== TuTech/DasCMS/System/Applications/Templates.bap/Application.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bambus SYSTEM "../../Resource/DTD/application_v1.dtd">
<bambus>
	<appController guid="org.bambuscms.applications.templates">ATemplates</appController>
	<name>templates</name>
	<description>edit_templates</description>
	<icon>app-utilities-editor-template</icon>
	<version>0.1.20081017</version>
	<priority>2.0</priority>
	<purpose>manage_content</purpose>
	<tabs>
		<tab icon="action-edit">edit</tab>
	</tabs>
	<application>
		<controller>controller.php</controller>
		<interface name="edit" src="edit.php">
			<panel name="content_actions">
				<task type="button" hotkey="o" caption="open" icon="action-document-open" action="org.bambuscms.wopenfiledialog.toggle();" />
				<task type="button" hotkey="s" caption="save" icon="action-document-save" action="org.bambuscms.app.document.save()" />
				<task type="button" hotkey="S" caption="save_and_rename" icon="action-document-save-as" action="org.bambuscms.app.document.saveAs('filename')" />
			</panel>
			<panel name="server_actions">
				<task type="button" hotkey="N" caption="new" icon="action-document-new" action="Create()" />
				<task type="button" hotkey="X" caption="delete" icon="action-edit-delete" action="Delete()" />
			</panel>
			<panel name="document_actions">
				<task type="button" hotkey="C" caption="cleanup" icon="action-edit-clean" action="org.bambuscms.app.document.cleanHTML('')" />
				<task type="button" hotkey="R" caption="search_and_replace" icon="action-edit-find-replace" action="org.bambuscms.app.document.searchAndReplace()" />
			</panel>
		</interface>
	</application>
</bambus>

=== TuTech/DasCMS/System/Applications/TextBricks.bap/Application.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bambus SYSTEM "../../Resource/DTD/application_v1.dtd">
<bambus>
	<appController guid="org.bambuscms.applications.textbricks">ATextBricks</appController>
	<name>text_bricks</name>
	<description>edit_text_bricks</description>
	<icon>app-text-bricks</icon>
	<version>0.1.20090310</version>
	<priority>2.0</priority>
	<purpose>manage_content</purpose>
	<tabs>
		<tab icon="action-edit">edit</tab>
	</tabs>
	<application>
		<controller>controller.php</controller>
		<interface name="edit" src="edit.php">
			<task type="button" hotkey="o" caption="open" icon="action-document-open" action="org.bambuscms.wopenfiledialog.toggle();" />
			<task type="button" hotkey="s" caption="save" icon="action-document-save" action="org.bambuscms.app.document.save()" />
			<task type="button" hotkey="S" caption="save_and_rename" icon="action-document-save-as" action="org.bambuscms.app.document.saveAs('filename')" />
			<task type="button" hotkey="N" caption="new" icon="action-document-new" action="Create()" />
			<task type="button" hotkey="X" caption="delete" icon="action-edit-delete" action="Delete()" />
			<task type="spacer" />
			<task type="button" hotkey="C" caption="cleanup" icon="action-edit-clean" action="org.bambuscms.app.document.cleanHTML('')" />
			<task type="button" hotkey="R" caption="search_and_replace" icon="action-edit-find-replace" action="org.bambuscms.app.document.searchAndReplace()" />
		</interface>
	</application>
</bambus>

=== TuTech/DasCMS/System/Applications/Configuration.bap/Application.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bambus SYSTEM "../../Resource/DTD/application_v1.dtd">
<bambus>
	<appController guid="org.bambuscms.applications.configuration">AConfiguration</appController>
	<name>configuration</name>
	<description>edit_configuration</description>
	<icon>app-preferences-enviornment</icon>
	<version>0.10.20061011</version>
	<priority>1.9</priority>
	<purpose>system</purpose>
	<tabs>
		<tab icon="action-edit">edit</tab>
	</tabs>
	<application>
		<controller>controller.php</controller>
		<interface name="edit" src="edit.php">
			<task type="button" hotkey="s" caption="save"
				icon="action-document-save" action="org.bambuscms.app.document.save()" />
		</interface>
	</application>
</bambus>
