=== TuTech/DasCMS/System/Resource/DTD/application.dtd
<!ELEMENT application (meta, window+)>
    <!ELEMENT meta (name, description, icon, version, guid, categories)>
        <!ELEMENT name          (#PCDATA)>
        <!ELEMENT description   (#PCDATA)>
        <!ELEMENT icon          (#PCDATA)>
        <!ELEMENT version       (#PCDATA)>
        <!ELEMENT guid          (#PCDATA)>
        <!ELEMENT categories    (category+)>
            <!ELEMENT category  EMPTY>
            <!ATTLIST category 
                name CDATA #REQUIRED
            >
    <!ELEMENT window (controller, view)>
    <!ATTLIST window 
        title CDATA #REQUIRED
        icon CDATA #REQUIRED
     >
        <!ELEMENT controller EMPTY>
        <!ATTLIST controller 
            src CDATA #REQUIRED
        >
        <!ELEMENT view EMPTY>
        <!ATTLIST view 
            type (php|xml|tpl) #REQUIRED
            src  CDATA #REQUIRED
        >

=== TuTech/DasCMS/System/Applications/Configuration.bap/Configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE application SYSTEM "../../Resource/DTD/application.dtd">
<application>
    <meta>
        <name>configuration</name>
        <description>edit_configuration</description>
        <icon>app-preferences-enviornment</icon>
        <version>0.10.20061011</version>
        <guid>org.bambuscms.configuration</guid>
        <categories>
            <category name="system" />
        </categories>
    </meta>
    <window title="edit" icon="action-edit">
        <controller src="controller.php" />
        <view src="edit.php" type="php" />
    </window>
</application>
